version: '3.9'
services:
  sh:
    image: ghcr.io/brainstation-au/dbt-bigquery:main
    # build: .
    volumes:
      - $HOME/.dbt:/root/.dbt
      - $HOME/.gcp:/root/.gcp
      - .:/opt/code
    working_dir: /opt/code
    command: bash
